const CITY_SEARCH_STARTED = 'CITY_SEARCH_STARTED';
const CITY_SEARCH_FINISHED = 'CITY_SEARCH_FINISHED';
const CITY_SEARCH_ERROR = 'CITY_SEARCH_ERROR';

export { CITY_SEARCH_STARTED, CITY_SEARCH_FINISHED, CITY_SEARCH_ERROR };
