const SELECT_CITY = 'SELECT_CITY';
const CITY_DOWLOADING_START = 'CITY_DOWLOADING_START';
const CITY_DOWLOADING_SUCCESSED = 'CITY_DOWLOADING_SUCCESSED';
const CITY_DOWLOADING_ERROR = 'CITY_DOWLOADING_ERROR';

export { SELECT_CITY, CITY_DOWLOADING_START, CITY_DOWLOADING_SUCCESSED, CITY_DOWLOADING_ERROR };
