const QUALITY_ANCHOR = 'quality';
const LOCATION_ANCHOR = 'location';
const CULTURE_ANCHOR = 'culture';
const CLIMATE_ANCHOR = 'climate';
const LIFE_QUALITY_ANCHOR = 'life Quality';
const HOUSING_ANCHOR = 'housing';
const COST_OF_LIVING_ANCHOR = 'cost Of Living';

const ALL_ANCHORS = [
  QUALITY_ANCHOR,
  LOCATION_ANCHOR,
  CULTURE_ANCHOR,
  CLIMATE_ANCHOR,
  LIFE_QUALITY_ANCHOR,
  HOUSING_ANCHOR,
  COST_OF_LIVING_ANCHOR,
];

export {
  ALL_ANCHORS,
  QUALITY_ANCHOR,
  LOCATION_ANCHOR,
  CULTURE_ANCHOR,
  CLIMATE_ANCHOR,
  LIFE_QUALITY_ANCHOR,
  HOUSING_ANCHOR,
  COST_OF_LIVING_ANCHOR,
};
