const BUSINESS_FREEDOM = 'BUSINESS-FREEDOM';
const CITY_SIZE = 'CITY-SIZE';
const CLIMATE = 'CLIMATE';
const COST_OF_LIVING = 'COST-OF-LIVING';
const CULTURE = 'CULTURE';
const ECONOMY = 'ECONOMY';
const EDUCATION = 'EDUCATION';
const HEALTHCARE = 'HEALTHCARE';
const HOUSING = 'HOUSING';

export {
  BUSINESS_FREEDOM,
  CITY_SIZE,
  CLIMATE,
  COST_OF_LIVING,
  CULTURE,
  ECONOMY,
  EDUCATION,
  HEALTHCARE,
  HOUSING,
};
