const CITY_LIST_LOADING_START = 'CITY_LIST_LOADING_START';
const CITY_LIST_LOADING_SUCCESSED = 'CITY_LIST_LOADING_SUCCESSED';
const CITY_LIST_ADD_CITIES = 'CITY_LIST_ADD_CITIES';
const CITY_LIST_CHANGE_FILTER_TYPE = 'CITY_LIST_CHANGE_FILTER_TYPE';
const CITY_LIST_LOADING_ERROR = 'CITY_LIST_LOADING_ERROR';

export {
  CITY_LIST_LOADING_START,
  CITY_LIST_LOADING_SUCCESSED,
  CITY_LIST_ADD_CITIES,
  CITY_LIST_CHANGE_FILTER_TYPE,
  CITY_LIST_LOADING_ERROR,
};
