const CITY_LIST_DOWLOADING_START = 'CITY_LIST_DOWLOADING_START';
const CITY_LIST_DOWLOADING_SUCCESSED = 'CITY_LIST_DOWLOADING_SUCCESSED';
const CITY_LIST_ADD_CITIES = 'CITY_LIST_ADD_CITIES';
const CITY_LIST_CHANGE_FILTER_TYPE = 'CITY_LIST_CHANGE_FILTER_TYPE';
const CITY_LIST_DOWLOADING_ERROR = 'CITY_LIST_DOWLOADING_ERROR';

export {
  CITY_LIST_DOWLOADING_START,
  CITY_LIST_DOWLOADING_SUCCESSED,
  CITY_LIST_ADD_CITIES,
  CITY_LIST_CHANGE_FILTER_TYPE,
  CITY_LIST_DOWLOADING_ERROR,
};
